---
gcp_credentials: ENCRYPTED[!149d4005ecdba4cdd78bb5ba22756ebb98bf8e3367ee2e9ab08c5a1608c0d3e3b501904b67a1d67c0b63085e469d7dde!]

env:
  ARTIFACTORY_PRIVATE_USERNAME: vault-sonarsource-parent-oss-private-reader
  ARTIFACTORY_DEPLOY_USERNAME: vault-sonarsource-parent-oss-qa-deployer
  # Possible values for ARTIFACTORY_DEPLOY_REPO: sonarsource-private-qa, sonarsource-public-qa
  ARTIFACTORY_DEPLOY_REPO: sonarsource-public-qa
  ARTIFACTORY_API_KEY: ENCRYPTED[!53f27f70135e2248b0b371dab726b209733c33adeef00a345f7ddae24108b22caca6e498de8843d4252a3671813ce371!]

container_definition: &CONTAINER_DEFINITION
  image: eu.gcr.io/release-engineering-ci-prod/base:j11-latest
  cluster_name: cirrus-ci
  zone: europe-west4-b
  namespace: default

only_sonarsource_qa: &ONLY_SONARSOURCE_QA
  only_if: >
    $CIRRUS_USER_COLLABORATOR == 'true' && 
    $CIRRUS_TAG == "" && 
    ($CIRRUS_PR != "" 
    || $CIRRUS_BRANCH == 'master' 
    || $CIRRUS_BRANCH =~ "branch-.*" 
    || $CIRRUS_BRANCH =~ "dogfood-on-.*" 
    || $CIRRUS_BUILD_SOURCE == 'api' 
    )

vault: &VAULT
  vault_script:
    - vault.sh

build_task:
  <<: *ONLY_SONARSOURCE_QA
  gke_container:
    <<: *CONTAINER_DEFINITION
    cpu: 2
    memory: 2G
  env:
    # analysis on next
    SONAR_HOST_URL: https://next.sonarqube.com/sonarqube
    # allow deployment of pull request artifacts to repox
    DEPLOY_PULL_REQUEST: true
    CIRRUS_CLONE_DEPTH: 50
  <<: *VAULT
  maven_cache:
    folder: ${CIRRUS_WORKING_DIR}/.m2/repository
  build_script:
    - source cirrus-env BUILD
    - regular_mvn_build_deploy_analyze
  cleanup_before_cache_script: cleanup_maven_repository

promote_task:
  depends_on:
    - build
  <<: *ONLY_SONARSOURCE_QA
  gke_container:
    <<: *CONTAINER_DEFINITION
    cpu: 1
    memory: 1G
  env:
    # artifacts that will have downloadable links in burgr
    ARTIFACTS: org.sonarsource.parent:parent:pom
  <<: *VAULT
  maven_cache:
    folder: ${CIRRUS_WORKING_DIR}/.m2/repository
  script: cirrus_promote_maven
  cleanup_before_cache_script: cleanup_maven_repository
