name: Pre-commit checks
on:
  pull_request:
  merge_group:

jobs:
  pre-commit:
    name: "pre-commit"
    runs-on: github-ubuntu-latest-s
    steps:
      - uses: SonarSource/gh-action_pre-commit@698a883e4d3a697bee22e5e16dff6b2f9572f44d # 1.2.2
        with:
          extra-args: >
            --from-ref=origin/${{ github.event.pull_request.base.ref }}
            --to-ref=${{ github.event.pull_request.head.sha }}
