name: Pre-commit checks
on:
  pull_request:
  merge_group:

jobs:
  pre-commit:
    name: "pre-commit"
    runs-on: github-ubuntu-latest-s
    steps:
      - uses: SonarSource/gh-action_pre-commit@1181d422cbd3380624656c4dc46f6172263c0418 # 2.0.0
        with:
          extra-args: >
            --from-ref=origin/${{ github.event.pull_request.base.ref }}
            --to-ref=${{ github.event.pull_request.head.sha }}
