name: Pre-commit checks
on:
  pull_request:
  merge_group:

jobs:
  pre-commit:
    name: "pre-commit"
    runs-on: ubuntu-24.04-large
    steps:
      - uses: SonarSource/gh-action_pre-commit@fc9d73025994fd1c2b96d568c8c8a4af82a3ae21 # 1.0.6
        with:
          extra-args: >
            --from-ref=origin/${{ github.event.pull_request.base.ref }}
            --to-ref=${{ github.event.pull_request.head.sha }}
