name: Pre-commit checks
on:
  pull_request:
  merge_group:

jobs:
  pre-commit:
    name: "pre-commit"
    runs-on: ubuntu-latest
    steps:
      - uses: SonarSource/gh-action_pre-commit@469b062f5c72f80612f6ba51e8191524eba7d3b8 # 1.0.5
        with:
          extra-args: >
            --from-ref=origin/${{ github.event.pull_request.base.ref }}
            --to-ref=${{ github.event.pull_request.head.sha }}
