on:
  pull_request:
  merge_group:
  push:
    branches:
      - master

name: pre-commit

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  pre-commit:
    runs-on: sonar-xs
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: SonarSource/gh-action_pre-commit@v2
