---
name: sonar-release
# This workflow is triggered when publishing a new github release
# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@8d4ccba8d0b6485e7d15c896b72d69ca1e513bcc # 5.9.5
    with:
      publishToBinaries: false
      mavenCentralSync: true
