---
name: sonar-release
# This workflow is triggered when publishing a new github release
# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@c656d07bb87d435d3a89610af32b33988daa0eff # 5.11.0
    with:
      publishToBinaries: false
      mavenCentralSync: true
