name: Unified Dogfooding scans

on:
  schedule:
    - cron: '0 4 * * *'  # Daily at 04:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: github-ubuntu-latest-s
    name: Build and run shadow scans
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
        with:
          version: 2025.7.12
      - uses: SonarSource/ci-github-actions/build-maven@v1
        with:
          run-shadow-scans: true
          artifactory-reader-role: private-reader
          maven-args: -Dsonar.organization=sonarsource -Dsonar.projectKey=SonarSource_parent-oss
